//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public int MaNV { get; set; }
        public string Ho_ten { get; set; }
        public string Chuc_vu { get; set; }
        public decimal Luong { get; set; }
        public System.DateTime Ngay_vao_lam { get; set; }
    }
}
